SpeedControllers
FRC125/FRamework pull request #34
Opened 2017-01-24 03:18 UTC by totallyashes

Added speed controller event system, and overall improvements to factories and the functionality of StreamManager and Robot for the user.

2017-01-24 04:24 UTC, MiloDavis requested changes
Mostly small changes.  This review was a little cursory, try to have @kreeve look at it as well.

2017-01-24 04:24 UTC, MiloDavis commented on build.properties
> +userLibInstallCtre.URL=http://www.ctr-electronics.com/downloads/lib/CTRE_FRCLibs_NON-WINDOWS_v4.4.1.9.zip
Does this work on Windows?

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/consumers/ControllerEvent.java
> +  class EventUnimplementedException extends RuntimeException {
This should probably be public

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/consumers/ControllerEvent.java
> +      super("Controller \"" + controller +
Use String.format here

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/consumers/LoopPropertiesEvent.java
> +  public LoopPropertiesEvent(double setpoint, double kP, double kI, double kD, double kF) {
Break the paraemters onto separate lines for readability

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/InputManager.java
> +      throw new RuntimeException("The default InputFactory HAS NOT been set!");
This should be an `IllegalStateException`

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/OutputManager.java
> +      throw new RuntimeException("The default OutputFactory has ALREADY been set!");
This should be an `IllegalStateException`

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/OutputManager.java
> +      throw new RuntimeException("The default OutputFactory HAS NOT been set!");
This should be an `IllegalStateException`

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/WPIFactory.java
> +  @Override
No magic numbers, make the 0, 4, 1, and 5 constants.

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/WPIFactory.java
> +        throw new RuntimeException("Controller on port "
This should be an `IllegalStateException`

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/WPIFactory.java
> +        throw new RuntimeException("Controller on port "
Also, use `String.format`

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/WPIFactory.java
> +      throw new RuntimeException("Controller on port "
Use `IllegalStateException` and `String.format`

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/WPIFactory.java
> +      throw new RuntimeException("Settings instance has already been set");
This should be an `IllegalStateException`

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/factories/WPIFactory.java
> +      throw new RuntimeException("Settings instance hasn't been set");
This should be an `IllegalStateException`

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/DictionarySettings.java
> +  public void registerSubscriptions() {
This method is not abstract.  Don't override unless you're modifying the behavior.

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/WPISettings.java
> +        500, TimeUnit.MILLISECONDS);
Pull the 500 out into a constant.

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/WPISettings.java
> +    ints.put(key, prefs.getInt(key, ints.containsKey(key) ? ints.get(key) : 0));
Use `getOrDefault` here

2017-01-24 04:24 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/WPISettings.java
> +    doubles.put(key, prefs.getDouble(key, doubles.containsKey(key) ? doubles.get(key) : 0.0));
Use `getOrDefault` here

2017-01-24 23:19 UTC, totallyashes commented on build.properties
> +userLibInstallCtre.URL=http://www.ctr-electronics.com/downloads/lib/CTRE_FRCLibs_NON-WINDOWS_v4.4.1.9.zip
99% sure. This is the version that doesn't come with the windows installer, and just lets you get files that you can place manually.

2017-01-25 00:12 UTC, kreeve commented on build.properties
> +userLibInstallCtre.URL=http://www.ctr-electronics.com/downloads/lib/CTRE_FRCLibs_NON-WINDOWS_v4.4.1.9.zip
Yeah it does, I've tested it

2017-01-27 17:50 UTC, MiloDavis approved these changes

2017-01-27 17:50 UTC, merged