Serial
FRC125/FRamework pull request #42
Opened 2017-01-29 19:50 UTC by cappuccinocat

2017-01-29 22:31 UTC, MiloDavis requested changes

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +    public Serial(SerialPort.Port port, int bufferSize, int packetLength, char terminationCharacter) {
Import `Port`

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +        this(9600, port, bufferSize, packetLength, terminationCharacter);
Does the baud rate need to be constant, or is it just here to match the arduino?

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +     * Create Serial streams from a WPI "Serial"
What's with the quotes?

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +            serial.enableTermination();
Check the source to see if `enableTermination()` is implemented as a convenience wrapper around `enableTermination(char terminationChar)`.  If they're the same, simplify this.

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +            serial.enableTermination();
Or just simplify this anyway, it shouldn't matter much.

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/Settings.java
> +        return FlowOperators.toFlow( () ->Preferences.getInstance().getDouble(key, 0.0) ).distinctUntilChanged();
Redo formatting of this line

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/Settings.java
> +    public void registerSubscriptions() {
If this is intentionally left empty, add a comment to that effect

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/util/FlowOperators.java
> +  public static Flowable<Double> deadzone(Flowable<Double> input) {
This needs JavaDoc

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/util/FlowOperators.java
> +  public static Flowable<Double> deadzone(Flowable<Double> input) {
This method is also usually referred to as deadband

2017-01-29 22:31 UTC, MiloDavis commented on src/com/nutrons/framework/util/FlowOperators.java
>     * Generate a Flowable from a periodic call to a Supplier.
Add additional method that allows for varying time amounts

2017-01-30 23:16 UTC, cappuccinocat commented on src/com/nutrons/framework/producers/Serial.java
> +        this(9600, port, bufferSize, packetLength, terminationCharacter);
It's just the default in case users are too lazy to set it themselves w/ the other constructor

2017-01-30 23:19 UTC, cappuccinocat commented on src/com/nutrons/framework/util/FlowOperators.java
>     * Generate a Flowable from a periodic call to a Supplier.
Not the purpose of this pull request, maybe in another branch will do
I'm not sure why the time was set as such and so I don't think I should edit it

2017-01-31 00:29 UTC, MiloDavis requested changes

2017-01-31 00:29 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +      this.values = FlowOperators.toFlow( () -> this.button.get());
No space before `()`

2017-01-31 00:29 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +        this(9600, SerialPort.Port.kUSB, bufferSize, packetLength, '\n');
The `terminationCharacter` parameter is unused.  You have a convenience constructor which sets it to a default

2017-01-31 00:29 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +        this(9600, SerialPort.Port.kUSB, bufferSize, packetLength, '\n');
These constructors need javadoc

2017-01-31 00:29 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +        this(9600, port, bufferSize, packetLength, terminationCharacter);
Define `DEFAULT_BAUD_RATE` as a constant

2017-01-31 00:29 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +    public Serial(int baudrate, SerialPort.Port port, int bufferSize, int packetLength, char terminationCharacter) {
Split onto separate lines

2017-01-31 00:29 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/Settings.java
> +        return FlowOperators.toFlow( () ->Preferences
Space before `()`

2017-01-31 00:29 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/Settings.java
> +        //TODO: don't emit anything if it's 0.0, store last value and send that as backup
Do this

2017-01-31 01:01 UTC, cappuccinocat commented on src/com/nutrons/framework/subsystems/Settings.java
> +        //TODO: don't emit anything if it's 0.0, store last value and send that as backup
I'm not sure how to do this yet - I'll leave this as a TODO until I consult a mentor/Asher

2017-02-01 23:35 UTC, MiloDavis requested changes

2017-02-01 23:35 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
>      public WpiButton(WpiGamepad joystick, int buttonNumber){
Change parameter to `gamePad`

2017-02-01 23:35 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
>      public WpiButton(WpiGamepad joystick, int buttonNumber){
Move separate file

2017-02-01 23:35 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
Unnecessary import?

2017-02-01 23:35 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
> +     * @param packetLength represents the length of each read from the buffer
Add javadoc for terminationCharacter

2017-02-01 23:35 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
>      public Serial(SerialPort.Port port, int bufferSize, int packetLength, char terminationCharacter) {
Stack these parameters

2017-02-01 23:35 UTC, MiloDavis commented on src/com/nutrons/framework/producers/Serial.java
>       * Create Serial streams from a WPI Serial
Add javadoc for `baudrate`

2017-02-01 23:35 UTC, MiloDavis commented on src/com/nutrons/framework/subsystems/Settings.java
> +        return FlowOperators.toFlow(() ->Preferences
Space on other side of arrow

2017-02-03 00:37 UTC, MiloDavis requested changes

2017-02-03 00:37 UTC, MiloDavis commented on src/com/nutrons/framework/controllers/RunAtPowerEvent.java
> +   * TODO make sure Talons use power from -1.0 to 1.0,
Do this

2017-02-03 00:37 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/Serial.java
> +    this(DEFAULT_BAUD_RATE, SerialPort.Port.kUSB, bufferSize, packetLength, '\n');
Move `\n` to `DEFAULT_TERMINATION_CHARACTER`

2017-02-03 00:37 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/Serial.java
> +      return serial.read(packetLength);
Does this block?  If the serial drops out, is it possible that this will hang?

2017-02-03 00:37 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +  public Flowable<Boolean> button(int buttonNumber) {
Rework this into the actual double check pattern or collapse into one function

2017-02-03 00:37 UTC, MiloDavis commented on src/com/nutrons/framework/util/FlowOperators.java
> +  public static Flowable<Double> deadband(Flowable<Double> input) {
Add second function `deadbandMap` which is the lambda so you can do the transformation as a map instead of a wrapping function call.

2017-02-04 15:54 UTC, cappuccinocat commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +  public Flowable<Boolean> button(int buttonNumber) {
already done by someone

2017-02-04 15:54 UTC, cappuccinocat commented on src/com/nutrons/framework/util/FlowOperators.java
> +  public static Flowable<Double> deadband(Flowable<Double> input) {
not sure what this means here

2017-02-04 16:39 UTC, MiloDavis approved these changes

2017-02-04 16:39 UTC, merged