Added unresolved dependency
FRC125/FRamework pull request #6
Opened 2017-01-13 01:09 UTC by totallyashes

2017-01-13 01:14 UTC, kreeve requested changes
Add a test!

2017-01-14 18:18 UTC, Jw0x47 requested changes

2017-01-14 18:18 UTC, jonathanwgoodwin commented on src/com/nutrons/FRamework/input/InputFactory.java
> +
nit. `\n`

2017-01-14 18:18 UTC, jonathanwgoodwin commented on .travis.yml
> +  - cat wpilib/ant/build.xml
Should probably remove these.

2017-01-14 19:12 UTC, kreeve approved these changes

2017-01-14 19:12 UTC, merged