CommonController
FRC125/FRamework pull request #62
Opened 2017-02-12 17:56 UTC by AndreasLc1103

A class that eliminates having to Re-Map controller inputs for different controllers

2017-02-12 21:22 UTC, kreeve submitted a review, later dismissed

2017-02-12 21:22 UTC, kreeve commented on src/com/nutrons/framework/inputs/CommonController.java
> +                           int ButtonSelect,
random capitalized argument

2017-02-12 21:22 UTC, kreeve commented on src/com/nutrons/framework/inputs/CommonController.java
> +  public static CommonController logitechF310(int port) {
We should cache the controller instance if possible

2017-02-13 16:50 UTC, totallyashes commented on src/com/nutrons/framework/inputs/CommonController.java
> +  public static CommonController logitechF310(int port) {
Not realistic, because it is a pain to handle if they try to make logitechF310 and xbox360 on the same port. leave like this for now.

2017-02-13 19:22 UTC, MiloDavis requested changes

2017-02-13 19:22 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/CommonController.java
> +        InputMap.LOGITECH__SELECT,
Why two underscores?

2017-02-13 19:22 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/CommonController.java
> +  private int buttonX;
These should all be final

2017-02-13 19:22 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +                  this.joystick.getRawAxis(axisNumber)).onBackpressureDrop().publish());
remove `onBackpressureDrop` this is now added by toFlow

2017-02-13 19:22 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +                  .distinctUntilChanged().onBackpressureDrop().publish());
Remove `onBackpressureDrop` this is now added by default

2017-02-13 20:51 UTC, MiloDavis requested changes
Clear out the nonsense and we can merge.

2017-02-13 20:51 UTC, MiloDavis commented on src/com/nutrons/framework/controllers/Events.java
> +import java.awt.*;
No wildcard imports

2017-02-13 20:51 UTC, MiloDavis commented on src/com/nutrons/framework/controllers/Events.java
> +import java.awt.*;
And what are you using this for?

2017-02-13 20:51 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/CommonController.java
> +
Extra linebreak

2017-02-13 23:58 UTC, MiloDavis requested changes

2017-02-13 23:58 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +      synchronized (lock) {
This needs to be done using real concurrency primitives

2017-02-13 23:58 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +      synchronized (lock) {
@totallyashes

2017-02-13 23:58 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +      synchronized (lock) {
Real concurrency primitives

2017-02-14 00:38 UTC, MiloDavis requested changes

2017-02-14 00:38 UTC, MiloDavis commented on src/com/nutrons/framework/inputs/WpiGamepad.java
> +  private final RegisteredLock lock = new RegisteredLock();
Move into constructor

2017-02-14 16:36 UTC, kreeve approved these changes

2017-02-14 16:45 UTC, MiloDavis approved these changes

2017-02-14 16:45 UTC, merged