Master Version of ToFlowSafe Version Compreet
FRC125/FRamework pull request #65
Opened 2017-02-13 17:36 UTC by JYoung413

Same thing I did in toFlowModification branch but without a bunch of other files just things merged into master

2017-02-13 19:02 UTC, MiloDavis requested changes

2017-02-13 19:02 UTC, MiloDavis commented on src/com/nutrons/framework/util/FlowOperators.java
> +    return toFlowBackpressure(supplier, ignored, unit).onBackpressureDrop();
Why is this parameter called ignored?

2017-02-13 19:02 UTC, MiloDavis commented on src/com/nutrons/framework/util/FlowOperators.java
> +  public static <T> Flowable<T> toFlowBackpressure(Supplier<T> supplier, long ignored, TimeUnit unit) {
`ignored` is still a weird parameter name

2017-02-13 19:02 UTC, MiloDavis commented on src/com/nutrons/framework/util/FlowOperators.java
> +  public static io.reactivex.functions.Function<Double, Double> deadbandMap(double minimum, double maximum, double remap) {
Use an import here

2017-02-13 19:02 UTC, MiloDavis commented on src/com/nutrons/framework/util/FlowOperators.java
> +  public static io.reactivex.functions.Function<Double, Double> bandMap(double minimum, double maximum, Function<Double, Double> remap) {
We were supposed to change the interface of `deadband`.  Is this in a different branch?

2017-02-14 00:48 UTC, kreeve commented
Is this needed anymore?

2017-02-14 04:35 UTC, MiloDavis approved these changes

2017-02-15 15:03 UTC, closed without merging