Made the FlowingPID Class essential for HoldHeading and other PID Stuff
FRC125/FRamework pull request #66
Opened 2017-02-13 17:45 UTC by JYoung413

This is just the FlowingPID class I made that takes pid values and an error streams and runs to get a proper control output. Only implementation right now is hold heading.

2017-02-13 23:58 UTC, kreeve requested changes

2017-02-13 23:58 UTC, kreeve commented on src/com/nutrons/framework/controllers/FlowingPID.java
> +
Get rid of random newlines

2017-02-15 16:44 UTC, ashergottlieb requested changes
As cool as flowing PID sounds, it's not really informative at all. Maybe like pid filter? I think you should move this to the utils package, perhaps incorporate into the flowoperators class, as a static method. It doesn't belong in the controllers package, since it isn't a speed controller. Also remove hard coded values, like 10, so it can really be a flexible tool.

2017-02-16 18:19 UTC, totallyashes commented
Closing this. Check #75.

2017-02-16 18:19 UTC, closed without merging