Added Combine method
FRC125/FRamework pull request #68
Opened 2017-02-13 19:07 UTC by AndreasLc1103

2017-02-13 20:38 UTC, MiloDavis requested changes

2017-02-13 20:38 UTC, MiloDavis commented on src/com/nutrons/framework/controllers/Events.java
> +import java.awt.*;
Don't use wildcard imports.

2017-02-13 20:38 UTC, MiloDavis commented on src/com/nutrons/framework/controllers/Events.java
> +        for (ControllerEvent E : Events) {
Use camel case variable names.  The first letter should be lowercase for everything but class names.  Then everything successive word should be capitalized.  Also, the google style guide does not allow for single letter variable names.

2017-02-14 00:44 UTC, kreeve approved these changes

2017-02-14 04:11 UTC, MiloDavis approved these changes

2017-02-14 04:11 UTC, merged